import {readFile, writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';

export const TITLE = 'Puro | Learn Finnish for Life, Study & Work';
export const DESCRIPTION = 'Learn Finnish with 60 guided lessons, vocabulary review, and speaking and writing practice. Build a steady habit for life, study, and work in Finland.';
export const IMAGE_ALT = 'Puro. Your next chapter. In Finnish. Forest green stream illustration with a pale green Puro mark.';
export const STRUCTURED_DATA = JSON.stringify({
  '@context': 'https://schema.org', '@type': 'WebApplication', name: 'Puro',
  description: DESCRIPTION, applicationCategory: 'EducationalApplication',
  operatingSystem: 'Web', inLanguage: 'en',
  browserRequirements: 'Requires JavaScript and an internet connection.'
});
export const STRUCTURED_HASH = 'sha256-' + createHash('sha256').update(STRUCTURED_DATA).digest('base64');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));

export function resolveSiteUrl(env = process.env) {
  const explicit = env.SITE_URL?.trim();
  const domain = env.VERCEL_PROJECT_PRODUCTION_URL?.trim();
  const candidate = explicit || (domain ? 'https://' + domain : '');
  if (!candidate) {
    if (env.VERCEL === '1') throw new Error('Production URL missing. Enable Vercel system environment variables, or set SITE_URL to your public HTTPS origin.');
    return '';
  }
  let url;
  try { url = new URL(candidate); } catch { throw new Error('SITE_URL must be a valid public HTTPS origin, such as https://your-project.vercel.app.'); }
  const labels = url.hostname.split('.');
  if (url.protocol !== 'https:' || url.username || url.password || url.port || url.pathname !== '/' || url.search || url.hash
    || labels.length < 2 || labels.some(label => !/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(label))
    || labels.every(label => /^\d+$/.test(label)) || /(?:^|\.)(localhost|local|supabase\.co)$/i.test(url.hostname)) {
    throw new Error('SITE_URL must be the public app’s HTTPS origin, without a path, port, credentials, query, or fragment. Do not use the Supabase URL.');
  }
  return url.origin;
}

export function metadata(env = process.env) {
  const origin = resolveSiteUrl(env);
  const indexable = Boolean(origin) && (!env.VERCEL_ENV || env.VERCEL_ENV === 'production');
  const image = origin + '/social/puro-og.png';
  const canonical = origin ? origin + '/' : '';
  const head = `<!-- Puro metadata:start -->
<meta name="theme-color" content="#183c35">
<meta name="color-scheme" content="light">
<meta name="description" content="${escape(DESCRIPTION)}">
<meta name="robots" content="${indexable ? 'index, follow, max-image-preview:large' : 'noindex, nofollow'}">
<meta name="application-name" content="Puro">
<title>${escape(TITLE)}</title>
${canonical ? `<link rel="canonical" href="${escape(canonical)}">\n<meta property="og:url" content="${escape(canonical)}">` : '<!-- Production canonical URL is generated by node build.mjs on Vercel. -->'}
<meta property="og:type" content="website">
<meta property="og:site_name" content="Puro">
<meta property="og:locale" content="en_GB">
<meta property="og:title" content="${escape(TITLE)}">
<meta property="og:description" content="${escape(DESCRIPTION)}">
<meta property="og:image" content="${escape(image)}">
${origin ? `<meta property="og:image:secure_url" content="${escape(image)}">\n` : ''}<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${escape(IMAGE_ALT)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${escape(TITLE)}">
<meta name="twitter:description" content="${escape(DESCRIPTION)}">
<meta name="twitter:image" content="${escape(image)}">
<meta name="twitter:image:alt" content="${escape(IMAGE_ALT)}">
<link rel="icon" type="image/png" href="/icons/favicon-96.png" sizes="96x96">
<link rel="icon" type="image/x-icon" href="/favicon.ico" sizes="16x16 32x32 48x48">
<link rel="icon" type="image/svg+xml" href="/favicon.svg" sizes="any">
<link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180">
<link rel="manifest" href="/site.webmanifest">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700&amp;display=swap">
<link rel="preload" as="image" href="/lake.jpg" fetchpriority="high">
<script type="application/ld+json">${STRUCTURED_DATA}</script>
<!-- Puro metadata:end -->`;
  const robots = indexable
    ? `User-agent: *\nAllow: /\n\nSitemap: ${canonical}sitemap.xml\n`
    : 'User-agent: *\nAllow: /\n';
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${indexable ? `\n  <url><loc>${escape(canonical)}</loc></url>\n` : ''}</urlset>\n`;
  return {head, robots, sitemap, origin, indexable};
}

export async function build(root = new URL('./', import.meta.url), env = process.env, requireOrigin = false) {
  const result = metadata(env);
  if (requireOrigin && !result.origin) throw new Error('Production URL missing. Enable Vercel system environment variables, or set SITE_URL to your public HTTPS origin.');
  const path = new URL('public/index.html', root);
  const html = await readFile(path, 'utf8');
  const marker = /<!-- Puro metadata:start -->[\s\S]*?<!-- Puro metadata:end -->/g;
  if ([...html.matchAll(marker)].length !== 1) throw new Error('Expected exactly one Puro metadata block in public/index.html.');
  const config = JSON.parse(await readFile(new URL('vercel.json', root), 'utf8'));
  const csp = config.headers.flatMap(rule => rule.headers).find(header => header.key === 'Content-Security-Policy')?.value;
  if (!csp?.includes(`'${STRUCTURED_HASH}'`)) throw new Error('The structured-data CSP hash is missing or outdated in vercel.json.');
  await writeFile(path, html.replace(marker, result.head));
  await writeFile(new URL('public/robots.txt', root), result.robots);
  await writeFile(new URL('public/sitemap.xml', root), result.sitemap);
  return result;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const {origin, indexable} = await build(undefined, process.env, process.argv.includes('--deploy'));
    console.log(`Puro metadata ready: ${origin || 'local preview'} (${indexable ? 'public entry page indexable' : 'noindex'}).`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
