import assert from 'node:assert/strict';
import {makeCloudStore} from './public/cloud.js';
import {emptyState} from './public/storage.js';
const memory=()=>{const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
let remote={data:emptyState('rajin'),revision:0},offline=false,calls=0;
const sdk={async rpc(name,args){calls++;if(offline)return {error:{message:'offline',code:'NETWORK'}};
 if(name==='puro_bootstrap')return {data:{...structuredClone(remote),slot:'rajin'}};
 if(args.expected_revision!==remote.revision)return {error:{code:'PT409'}};
 if(args.progress.owner!==user.id)return {error:{code:'42501'}};
 remote={data:structuredClone(args.progress.data),revision:remote.revision+1};return {data:{revision:remote.revision}};
}};
const local=memory(),user={id:'test-rajin'},store=makeCloudStore(sdk,user,'rajin',local);
assert.deepEqual(await store.load(),{data:emptyState('rajin'),revision:0});
const work={...emptyState('rajin'),journal:{'a1-hello':'Private writing'},review:{hei:{stage:0,due:0}}};
assert.deepEqual(await store.save(work,0),{revision:1});
assert.equal(store.cached().pending,false);
const secondDevice=makeCloudStore(sdk,user,'rajin',memory());
assert.deepEqual(await secondDevice.load(),{data:work,revision:1});
await assert.rejects(store.save(work,1,'labbaiqua'),/own account/);
assert.equal(remote.revision,1);
offline=true;
const newer={...work,journal:{'a1-hello':'Unsynced writing'}};
await assert.rejects(store.save(newer,1),/recovery copy/);
assert.equal(store.cached().pending,true);
assert.deepEqual(store.cached().data,newer);
offline=false;
assert.deepEqual(await store.load(),{data:newer,revision:2});
assert.equal(store.cached().pending,false);
await secondDevice.load();
await secondDevice.save({...newer,goal:15},2);
await assert.rejects(store.save({...newer,goal:45},2),e=>e.code===409);
assert.equal(remote.data.goal,15);
const recovered=await store.load();
assert.equal(recovered.conflict,true);
assert.equal(recovered.data.goal,45);
await store.discardPending();
assert([...local.map.keys()].some(k=>k.startsWith('puro:recovery:')));
assert.equal((await store.load()).data.goal,15);
const current=remote.revision;
const simultaneous=await Promise.allSettled([store.save(newer,current),store.save(newer,current)]);
assert.equal(simultaneous.filter(v=>v.status==='fulfilled').length,1);
assert.equal(simultaneous.find(v=>v.status==='rejected').reason.code,409);
const blocked=makeCloudStore(sdk,user,'rajin',{...memory(),setItem(){throw new Error('QuotaExceeded');}});
const before=calls;
await assert.rejects(blocked.save(work,remote.revision),/full or blocked/);
assert.equal(calls,before,'Never start a cloud save without the recovery copy');
const bad=makeCloudStore({rpc:async()=>({data:{slot:'rajin',data:{},revision:0}})},user,'rajin',memory());
await assert.rejects(bad.load(),/invalid learner/);
const changed=makeCloudStore(sdk,{id:'different-account'},'rajin',memory());
await assert.rejects(changed.save(work,remote.revision),e=>e.code==='42501');
const wrong=makeCloudStore(sdk,user,'labbaiqua',memory());
await assert.rejects(wrong.load(),/invalid learner/);
console.log('Passed: cloud saves, second-device loading, account isolation, failed-save recovery, stale revision protection, archived conflicts, concurrent saves, invalid cloud data, and full browser storage.');
